### PR TITLE
Definition file path property

### PR DESCRIPTION
**Pull request by anagaf**
Added Android project support.
Added definitionFilePath property support.
Modified to scan class-files only.
Modified to actually skip source set if no definition file available.
Added unit tests.

### CODE REVIEW

**Comment by konrad-garus** [comment]
Thanks for the contributions, some good changes there! Are you still interested in having it merged?

I assume you are using it with Android. I've never done that and don't have the time to figure it out and test. Is the Android support working well for you?

I'm still in two minds about having the Android dependency there, but maybe it's not such a big deal.

**Comment by anagaf** [comment]
Hi Konrad,

I work on both Android and Java EE projects so I need a universal plugin. I
had to create my own fork of your classycle-gradle-plugin:
https://github.com/anagaf/classycle-gradle-plugin

Regards,
Andrey

**Comment by konrad-garus** [comment]
Yeah, I noticed the fork, but could merge it back to avoid confusion in the community.

I am not opposed to Android, it is great to have that supported! Just something I can't test myself at this point, but I could trust you on this one. :-)

I only want to make sure that it still works well on non-Android projects and then I could merge it.

**Comment by anagaf** [comment]
Are you ok with the changes I made?

AA

**Comment by konrad-garus** [comment]
I like the idea, I have not fully reviewed the code and how it works yet. I'd like to keep the name (pl.squirrel) though.

**Comment by anagaf** [comment]
Ok, I will prepare new pull request

AA

**Comment by anagaf** [comment]
Are you ok with the changes? If yes could you merge the request asap? I would like to use it for my project

AA

**Pull request closed without merging**
